{{- if .Values.updateHook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ping.fullname" . }}-pre-upgrade-hook
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade-hook
        image: bash:5.1
        command: ["/bin/bash", "-c"]
        args:
          - |
            {{- .Values.updateHook.script | nindent 12 }}
